import { useEffect, useMemo, useState } from "react";
import { ArrowDown, ArrowUp, Check, Columns3, Grid2X2, List, Plus, RefreshCw, Search, Table2, Trash2 } from "lucide-react";
import { financeiro, vault, type CategoriaApi, type TransacaoApi } from "@/lib/api";
import { formatMoeda } from "@/lib/format";
import { useAppUI } from "@/lib/ui-context";
import type { Periodo } from "./types";
import type { Filtro } from "./VaultDashboard";
import { PeriodPicker } from "./nexus/PeriodPicker";
import type { Period } from "./nexus/period";

type Visualizacao="lista"|"tabela"; type Tipo="todos"|"entrada"|"saida"; type Status="todos"|"efetivada"|"pendente"; type Ordem="data"|"descricao"|"categoria"|"pagamento"|"valor";
const PAGAMENTOS:Record<string,string>={pix:"Pix",pix_automatico:"Pix automático",ted:"Transferência",cartao:"Cartão",dinheiro:"Dinheiro",boleto:"Boleto",outro:"Outro"};

export function VaultTransactions({recarregar,periodo,period,onPeriodChange,filtro,categorias,abrir,atualizar}:{recarregar:number;periodo:Periodo;period:Period;onPeriodChange:(p:Period)=>void;filtro:Filtro;categorias:CategoriaApi[];abrir:(id:string)=>void;atualizar:()=>void}) {
 const {abrirCaptura}=useAppUI(); const [rows,setRows]=useState<TransacaoApi[]>([]),[cursor,setCursor]=useState<string|null>(null),[selecionados,setSelecionados]=useState<string[]>([]); const [erro,setErro]=useState(""),[feedback,setFeedback]=useState(""),[ocupado,setOcupado]=useState(false),[carregando,setCarregando]=useState(true),[versao,setVersao]=useState(0);
 const [consulta,setConsulta]=useState(""),[tipo,setTipo]=useState<Tipo>(filtro.tipo??"todos"),[status,setStatus]=useState<Status>("todos"),[view,setView]=useState<Visualizacao>("lista"),[ordem,setOrdem]=useState<{chave:Ordem;dir:1|-1}>({chave:"data",dir:-1});
 const categoriasPorId=useMemo(()=>new Map(categorias.map(c=>[c.id,c])),[categorias]);
 const params={...periodo,tipo:filtro.tipo,limit:100,...(filtro.categoria===null?{sem_categoria:true}:filtro.categoria?{categoria_id:filtro.categoria}:{}),...(filtro.pagamento===null?{sem_pagamento:true}:filtro.pagamento?{forma_pagamento:filtro.pagamento}:{}),...(filtro.data_de?{data_de:filtro.data_de}:{}),...(filtro.data_ate?{data_ate:filtro.data_ate}:{})}, chave=JSON.stringify(params);
 useEffect(()=>{let vivo=true;setCarregando(true);setErro("");setRows([]);setSelecionados([]);setCursor(null);vault.transacoes.listar(JSON.parse(chave)).then(r=>{if(vivo){setRows(r.items);setCursor(r.next_cursor);}}).catch(e=>vivo&&setErro(e.message)).finally(()=>vivo&&setCarregando(false));return()=>{vivo=false;};},[chave,versao,recarregar]);
 const exibidas=useMemo(()=>{const q=consulta.trim().toLowerCase(),collator=new Intl.Collator("pt-BR");let lista=rows.filter(t=>(tipo==="todos"||t.tipo===tipo)&&(status==="todos"||t.status===status));if(q)lista=lista.filter(t=>`${t.descricao} ${t.observacoes??""} ${categoriasPorId.get(t.categoria_id??"")?.nome??""} ${PAGAMENTOS[t.forma_pagamento??""]??""}`.toLowerCase().includes(q));const texto=(t:TransacaoApi)=>ordem.chave==="categoria"?categoriasPorId.get(t.categoria_id??"")?.nome??"":ordem.chave==="pagamento"?PAGAMENTOS[t.forma_pagamento??""]??"":ordem.chave==="descricao"?t.descricao:t.data;return [...lista].sort((a,b)=>ordem.dir*(ordem.chave==="valor"?a.valor_centavos-b.valor_centavos:collator.compare(texto(a),texto(b))));},[rows,tipo,status,consulta,ordem,categoriasPorId]);
 async function mais(){if(!cursor)return;setOcupado(true);try{const r=await vault.transacoes.listar({...params,cursor});setRows(old=>[...old,...r.items]);setCursor(r.next_cursor);}catch(e){setErro((e as Error).message);}finally{setOcupado(false);}}
 async function lote(acao:"conciliar"|"desconciliar"|"excluir"){if(acao==="excluir"&&!window.confirm(`Excluir ${selecionados.length} lançamentos?`))return;setOcupado(true);setErro("");setFeedback("");try{const r=await financeiro.lote(selecionados,acao);if(r.erros.length)setErro(r.erros.map(e=>`Linha ${e.linha}: ${e.erro}`).join("; "));else setFeedback(`${r.aplicadas} operações aplicadas.`);setSelecionados([]);setVersao(v=>v+1);atualizar();}catch(e){setErro((e as Error).message);}finally{setOcupado(false);}}
 const selecionar=(id:string,v:boolean)=>setSelecionados(s=>v?[...s,id].slice(0,1000):s.filter(x=>x!==id)); const ordenar=(chave:Ordem)=>setOrdem(o=>o.chave===chave?{chave,dir:o.dir===1?-1:1}:{chave,dir:1});
 return <section className="cofre-transactions">
  <div className="cofre-transactions-top"><h1>Transações</h1><div className="cofre-transactions-actions"><label className="cofre-search"><Search size={15}/><input value={consulta} onChange={e=>setConsulta(e.target.value)} placeholder="Buscar transação…"/></label><PeriodPicker value={period} onChange={onPeriodChange}/><button className="cofre-new-button" onClick={()=>abrirCaptura("transacao")}><Plus size={14}/>Novo lançamento</button></div></div>
  <div className="cofre-transactions-toolbar"><div className="cofre-filter-group"><FiltroChip ativo={tipo==="todos"} onClick={()=>setTipo("todos")} icone={<Grid2X2 size={14}/>}>Todas</FiltroChip><FiltroChip ativo={tipo==="entrada"} onClick={()=>setTipo("entrada")} icone={<ArrowUp size={14}/>}>Apenas receitas</FiltroChip><FiltroChip ativo={tipo==="saida"} onClick={()=>setTipo("saida")} icone={<ArrowDown size={14}/>}>Apenas despesas</FiltroChip><span className="cofre-filter-divider"/><FiltroChip ativo={status==="efetivada"} onClick={()=>setStatus(status==="efetivada"?"todos":"efetivada")} icone={<Check size={14}/>}>Efetivadas</FiltroChip><FiltroChip ativo={status==="pendente"} onClick={()=>setStatus(status==="pendente"?"todos":"pendente")} icone={<Check size={14}/>}>Previstas</FiltroChip></div><div className="cofre-view-controls"><div className="cofre-view-toggle"><button aria-pressed={view==="lista"} onClick={()=>setView("lista")}><List size={14}/>Lista</button><button aria-pressed={view==="tabela"} onClick={()=>setView("tabela")}><Table2 size={14}/>Tabela</button></div><button className="cofre-columns-button" title="Colunas" aria-label="Configurar colunas"><Columns3 size={15}/></button></div></div>
  {erro&&<p role="alert" className="cofre-transactions-error">{erro}</p>}{feedback&&<p role="status" className="cofre-transactions-feedback">{feedback}</p>}
  {selecionados.length>0&&<div className="cofre-selection-bar"><b>{selecionados.length} selecionado{selecionados.length>1?"s":""}</b><span/><button onClick={()=>void lote("conciliar")}>Conciliar</button><button onClick={()=>void lote("desconciliar")}>Desconciliar</button><button className="danger" onClick={()=>void lote("excluir")}><Trash2 size={13}/>Excluir selecionados</button><button onClick={()=>setSelecionados([])}>Cancelar</button></div>}
  <div className="cofre-transactions-card">{carregando?<p className="cofre-table-empty">Carregando lançamentos…</p>:!exibidas.length?<p className="cofre-table-empty">Nenhum lançamento encontrado.</p>:view==="lista"?<div>{exibidas.map(t=><Linha key={t.id} t={t} categoria={categoriasPorId.get(t.categoria_id??"")} marcado={selecionados.includes(t.id)} selecionar={selecionar} abrir={abrir}/>)}</div>:<Tabela rows={exibidas} categorias={categoriasPorId} selecionados={selecionados} selecionar={selecionar} abrir={abrir} ordem={ordem} ordenar={ordenar}/>}</div>
  <div className="cofre-transactions-footer"><span>{exibidas.length} lançamento{exibidas.length===1?"":"s"}</span><button disabled={ocupado||carregando} onClick={()=>setVersao(v=>v+1)}><RefreshCw size={13}/>Atualizar</button>{cursor&&<button disabled={ocupado} onClick={()=>void mais()}>Carregar mais</button>}</div>
 </section>;
}
function FiltroChip({ativo,onClick,icone,children}:{ativo:boolean;onClick:()=>void;icone:React.ReactNode;children:React.ReactNode}){return <button className="cofre-filter-chip" aria-pressed={ativo} onClick={onClick}>{icone}{children}</button>;}
function Caixa({t,marcado,selecionar}:{t:TransacaoApi;marcado:boolean;selecionar:(id:string,v:boolean)=>void}){return <input type="checkbox" checked={marcado} onClick={e=>e.stopPropagation()} onChange={e=>selecionar(t.id,e.target.checked)} aria-label={`Selecionar ${t.descricao}`}/>;}
function Linha({t,categoria,marcado,selecionar,abrir}:{t:TransacaoApi;categoria?:CategoriaApi;marcado:boolean;selecionar:(id:string,v:boolean)=>void;abrir:(id:string)=>void}){return <div className={`cofre-transaction-list-row ${marcado?"selected":""}`} style={categoria?{boxShadow:`inset 3px 0 0 ${categoria.cor}`}:{}} onClick={()=>abrir(t.id)}><Caixa t={t} marcado={marcado} selecionar={selecionar}/><span className="cofre-category-dot" style={{background:categoria?.cor}}>{categoria?.nome.slice(0,1).toUpperCase()??"?"}</span><span className="cofre-transaction-description"><b>{t.descricao}</b><small>{PAGAMENTOS[t.forma_pagamento??""]??"Não informado"}</small></span><span className="cofre-transaction-category">{categoria?.nome??"Sem categoria"}</span><time>{t.data.split("-").reverse().join("/")}</time><strong data-tipo={t.tipo}>{t.tipo==="entrada"?"+":"−"}{formatMoeda(t.valor_centavos)}</strong><span className={`cofre-status ${t.status}`}>{t.status==="efetivada"?"Efetivada":"Prevista"}</span></div>;}
function Tabela({rows,categorias,selecionados,selecionar,abrir,ordem,ordenar}:{rows:TransacaoApi[];categorias:Map<string,CategoriaApi>;selecionados:string[];selecionar:(id:string,v:boolean)=>void;abrir:(id:string)=>void;ordem:{chave:Ordem;dir:1|-1};ordenar:(k:Ordem)=>void}){const cols:[Ordem,string][]=[["data","Data"],["descricao","Descrição"],["categoria","Categoria"],["pagamento","Pagamento"],["valor","Valor"]];return <div className="cofre-table-scroll"><table className="cofre-transactions-table"><thead><tr><th/><th/>{cols.map(([k,n])=><th key={k}><button onClick={()=>ordenar(k)}>{n}<span>{ordem.chave===k?(ordem.dir===1?"↑":"↓"):"↕"}</span></button></th>)}<th>Status</th></tr></thead><tbody>{rows.map(t=>{const cat=categorias.get(t.categoria_id??"");return <tr key={t.id} className={selecionados.includes(t.id)?"selected":""} onClick={()=>abrir(t.id)} style={cat?{boxShadow:`inset 3px 0 0 ${cat.cor}`}:{}}><td><Caixa t={t} marcado={selecionados.includes(t.id)} selecionar={selecionar}/></td><td><span className="cofre-category-dot" style={{background:cat?.cor}}>{cat?.nome.slice(0,1).toUpperCase()??"?"}</span></td><td>{t.data.split("-").reverse().join("/")}</td><td><b>{t.descricao}</b></td><td>{cat?.nome??"—"}</td><td>{PAGAMENTOS[t.forma_pagamento??""]??"—"}</td><td><strong data-tipo={t.tipo}>{t.tipo==="entrada"?"+":"−"}{formatMoeda(t.valor_centavos)}</strong></td><td><span className={`cofre-status ${t.status}`}>{t.status==="efetivada"?"Efetivada":"Prevista"}</span></td></tr>;})}</tbody></table></div>;}
