import { useEffect, useLayoutEffect, useRef, useState, type ReactNode } from "react";
import * as Icons from "lucide-react";
import { Check, ChevronDown, Coins, Copy, GalleryHorizontal, Plus, Send, Trash2, X } from "lucide-react";
import { SegmentedSlide } from "@/components/common/SegmentedSlide";
import { DatePicker } from "@/components/common/DatePicker";
import { formatMoeda } from "@/lib/format";
import { vault, type CategoriaApi, type ContaApi } from "@/lib/api";
import { useFormasPagamento } from "@/lib/formas-pagamento-store";
import { opcoesDoSeletor } from "@/lib/formas-pagamento";
import { SeloConta } from "@/screens/Vault/contas/SeloConta";
import type { CapturaDraft, SetDraft } from "./CreateFlow";
import { CampoValor } from "./CampoValor";
import { CampoCategoria } from "@/screens/Vault/CampoCategoria";
import { SugestaoCategoria } from "@/screens/Vault/SugestaoCategoria";

interface Props { slideChave?:string; slideDir?:"next"|"prev"; /** Liga/desliga o Modo Slide (andar pelos lançamentos da lista); só no editor de um lançamento. */ modoSlide?:{ativo:boolean;alternar:()=>void}; /** Faixa de navegação do Modo Slide, logo abaixo do cabeçalho. */ barraSlide?:ReactNode; draft:CapturaDraft; setDraft:SetDraft; onSalvar:()=>void; onFechar:()=>void; salvando?:boolean; eyebrow?:string; titulo?:string; rotuloSalvar?:string; erro?:string|null; onExcluir?:()=>void; /** Cria uma cópia (só na edição). */ onDuplicar?:()=>void; /** Abre o envio para o Cofre de outra equipe (só na edição). */ onEnviar?:()=>void; /** Nome de quem lançou (só em Cofre de equipe com mais de uma pessoa). Somente leitura. */ criadoPor?:string; /** Container de anexos, logo abaixo de Observações (o editor passa os anexos do lançamento; a criação, os pendentes). */ anexos?:React.ReactNode; }

export function TransactionForm({draft,setDraft,onSalvar,onFechar,salvando,eyebrow="NOVO REGISTRO",titulo="Novo lançamento",rotuloSalvar="Salvar lançamento",erro,onExcluir,onDuplicar,onEnviar,criadoPor,anexos,modoSlide,barraSlide,slideChave,slideDir}:Props) {
  const [confirmandoExcluir,setConfirmandoExcluir]=useState(false);
  const formas=useFormasPagamento();
  const opcoesForma=opcoesDoSeletor(formas.lista,draft.formaPagamento);
  // A forma atual do rascunho foi excluída por outra pessoa: o rascunho fica, mas não dá para salvar até escolher outra.
  const formaExcluida=!formas.indisponivel&&!!draft.formaPagamento&&!formas.porCodigo.has(draft.formaPagamento);
  const [categorias,setCategorias]=useState<CategoriaApi[]>([]),[contas,setContas]=useState<ContaApi[]>([]);
  useEffect(()=>{vault.categorias.listar().then(setCategorias).catch(()=>setCategorias([]));vault.contas.listar().then(lista=>{setContas(lista);const padrao=lista.find(c=>c.padrao)??lista[0];if(padrao&&!draft.contaId&&!onExcluir)setDraft(d=>({...d,contaId:padrao.id}));}).catch(()=>setContas([]));},[]); // eslint-disable-line react-hooks/exhaustive-deps
  const categoriasVisiveis=categorias.filter(c=>c.tipo==="ambos"||c.tipo===draft.tipoTransacao);
  function digitarValor(valor:string){const digitos=valor.replace(/\D/g,"").replace(/^0+/,"").slice(0,9);setDraft(d=>({...d,valorCentavos:Number(digitos||0)}));}
  const hojeISO=(()=>{const h=new Date();return `${h.getFullYear()}-${String(h.getMonth()+1).padStart(2,"0")}-${String(h.getDate()).padStart(2,"0")}`;})(),futuro=draft.dataTransacao>hojeISO;
  function mudarData(data:string){setDraft(d=>({...d,dataTransacao:data,...(data>hojeISO?{statusTransacao:"pendente" as const}:{})}));}
  useEffect(()=>{if(futuro&&draft.statusTransacao==="efetivada")setDraft(d=>({...d,statusTransacao:"pendente"}));},[futuro]); // eslint-disable-line react-hooks/exhaustive-deps
  const [lancando,setLancando]=useState(false),pode=!!draft.texto.trim()&&draft.valorCentavos>0&&!formaExcluida;
  function lancar(){if(lancando||salvando||!pode)return;if(window.matchMedia("(prefers-reduced-motion: reduce)").matches){onSalvar();return;}setLancando(true);window.setTimeout(()=>{onSalvar();setLancando(false);},780);}
  const valor=draft.valorCentavos>0?`${draft.tipoTransacao==="entrada"?"+":"−"}${formatMoeda(draft.valorCentavos)}`:"";
  async function adicionarCategoria(nome:string){const criada=await vault.categorias.criar({nome,tipo:draft.tipoTransacao,cor:draft.tipoTransacao==="entrada"?"#86d7ad":"#f29a9f",icone:draft.tipoTransacao==="entrada"?"TrendingUp":"ShoppingBag"});const lista=await vault.categorias.listar();setCategorias(lista);setDraft(d=>({...d,categoriaId:criada.id}));}
  return <form className="cofre-launch-form" onSubmit={e=>{e.preventDefault();lancar();}}>
    <header className="cofre-launch-header" data-window-drag-handle><div><p>{eyebrow}</p><h2>{titulo}</h2></div><div className="cofre-launch-header-actions">{modoSlide&&<button type="button" className="cofre-slide-toggle" data-ativo={modoSlide.ativo||undefined} aria-label="Modo Slide" aria-pressed={modoSlide.ativo} title={modoSlide.ativo?"Sair do Modo Slide":"Modo Slide: passar pelos lançamentos com as setas"} onClick={modoSlide.alternar}><GalleryHorizontal size={15}/></button>}{onEnviar&&<button type="button" aria-label="Enviar para outra equipe" title="Enviar para outra equipe" disabled={salvando} onClick={onEnviar}><Send size={15}/></button>}{onDuplicar&&<button type="button" aria-label="Duplicar" title="Duplicar" disabled={salvando} onClick={onDuplicar}><Copy size={15}/></button>}{onExcluir&&<button type="button" aria-label="Apagar" title="Apagar" onClick={()=>setConfirmandoExcluir(true)}><Trash2 size={15}/></button>}<button type="button" aria-label="Fechar" title="Fechar" onClick={onFechar}><X size={16}/></button></div></header>
    {barraSlide}
    <div className="cofre-launch-body" key={slideChave} data-slide-dir={slideChave?slideDir:undefined}>
      {criadoPor&&<p className="cofre-launch-author" aria-label="Criado por">Criado por <b>{criadoPor}</b></p>}
      {erro&&<p className="cofre-launch-alert" role="alert">{erro}</p>}
      {confirmandoExcluir&&onExcluir&&<div className="cofre-launch-alert" role="alert"><p>Apagar este lançamento? Essa ação não pode ser desfeita.</p><div><button type="button" onClick={()=>setConfirmandoExcluir(false)}>Cancelar</button><button type="button" disabled={salvando} onClick={onExcluir}>{salvando?"Apagando…":"Apagar"}</button></div></div>}
      <SegmentedSlide className="cofre-launch-slide" ariaLabel="Tipo do lançamento" tamanho="lg" value={draft.tipoTransacao} onChange={v=>setDraft(d=>({...d,tipoTransacao:v,categoriaId:null}))} opcoes={[{value:"saida",label:"Despesa",cor:"ecos-error"},{value:"entrada",label:"Receita",cor:"ecos-success"}]}/>
      <SegmentedSlide className="cofre-launch-slide" ariaLabel="Situação do lançamento" tamanho="lg" value={draft.statusTransacao} onChange={v=>{if(v==="efetivada"&&futuro)return;setDraft(d=>({...d,statusTransacao:v}));}} opcoes={[{value:"efetivada",label:"Efetivada",cor:"cofre-blue"},{value:"pendente",label:"Prevista",cor:"cofre-pink"}]}/>
      {futuro&&<p className="cofre-launch-dica-futuro">Data futura: fica como prevista até chegar o dia.</p>}
      {valor&&<strong className="cofre-launch-preview" data-tipo={draft.tipoTransacao}>{valor}</strong>}
      <div className="cofre-launch-fields">
        <div className="cofre-launch-grid"><Campo label="Valor"><CampoValor autoFocus={!modoSlide?.ativo} centavos={draft.valorCentavos} aoMudar={v=>setDraft(d=>({...d,valorCentavos:v}))}/></Campo><Campo label="Data" className="cofre-launch-date"><DatePicker value={draft.dataTransacao} onChange={mudarData}/></Campo></div>
        <Campo label="Descrição"><input value={draft.texto} onChange={e=>setDraft(d=>({...d,texto:e.target.value}))} placeholder="Ex.: Mercado Extra"/></Campo>
        <Campo label="Pagador / Recebedor"><input value={draft.beneficiarioNome} onChange={e=>setDraft(d=>({...d,beneficiarioNome:e.target.value}))} placeholder="Ex.: Mercado Extra Ltda"/></Campo>
        <Campo label="Categoria"><CampoCategoria categorias={categoriasVisiveis} valor={draft.categoriaId??null} onChange={value=>setDraft(d=>({...d,categoriaId:value}))} onCriar={adicionarCategoria}/><SugestaoCategoria pagador={draft.beneficiarioNome} descricao={draft.texto} tipo={draft.tipoTransacao} atual={draft.categoriaId} categorias={categorias} aoUsar={id=>setDraft(d=>({...d,categoriaId:id}))}/></Campo>
        <div className="cofre-launch-grid"><Campo label="Conta"><MenuSelecao value={draft.contaId??""} placeholder="Sem conta" options={contas.map(c=>({value:c.id,label:c.nome,cor:c.cor,selo:<SeloConta nome={c.nome} cor={c.cor} tipo={c.tipo} codigoBanco={c.codigo_banco} sigla={c.sigla} tamanho="xs"/>}))} onChange={value=>setDraft(d=>({...d,contaId:value||null}))}/></Campo><Campo label="Forma de pagamento"><MenuSelecao value={draft.formaPagamento??""} placeholder="Não informada" options={opcoesForma.map(o=>{const f=formas.porCodigo.get(o.codigo);return {value:o.codigo,label:o.inativa?`${o.nome} (inativa)`:o.nome,cor:f?.cor,icone:f?.icone};})} onChange={value=>setDraft(d=>({...d,formaPagamento:value||null}))}/>{formaExcluida&&<small className="cofre-launch-alert" role="alert">A forma “{draft.formaPagamento}” não existe mais. Escolha outra para salvar.</small>}</Campo></div>
        <Campo label="Observações"><textarea rows={3} value={draft.observacoesTransacao} onChange={e=>setDraft(d=>({...d,observacoesTransacao:e.target.value}))} placeholder="Opcional"/></Campo>
        {anexos}
      </div>
    </div>
    <footer className="cofre-launch-footer"><button data-tipo={draft.tipoTransacao} data-lancando={lancando} disabled={salvando||!pode||lancando}><span className="cofre-launch-label">{salvando?"Salvando…":rotuloSalvar}</span>{lancando&&<i className="cofre-launch-coin" aria-hidden="true"><b><Coins size={18} strokeWidth={2.2}/></b></i>}</button></footer>
  </form>;
}
function Campo({label,children,className}:{label:string;children:ReactNode;className?:string}){return <div className={`cofre-launch-field ${className??""}`}><span>{label}</span>{children}</div>;}
export function MenuSelecao({value,placeholder,options,onChange,onAdd,semVazio,ariaLabel}:{value:string;placeholder:string;options:{value:string;label:string;cor?:string|null;icone?:string|null;selo?:ReactNode}[];onChange:(value:string)=>void;onAdd?:(nome:string)=>Promise<void>;/** Sem a opção "vazia" no topo (campo obrigatório). */semVazio?:boolean;ariaLabel?:string}){
  const [aberto,setAberto]=useState(false),[adicionando,setAdicionando]=useState(false),[nome,setNome]=useState(""),[salvando,setSalvando]=useState(false),ref=useRef<HTMLDivElement>(null),listaRef=useRef<HTMLDivElement>(null),[pos,setPos]=useState<{acima:boolean;max:number}>({acima:false,max:190});const atual=options.find(o=>o.value===value);const IconeAtual=icone(atual?.icone);
  useLayoutEffect(()=>{if(!aberto||!ref.current||!listaRef.current)return;const corpo=ref.current.closest(".cofre-launch-body")??document.body,c=corpo.getBoundingClientRect(),b=ref.current.getBoundingClientRect(),abaixo=c.bottom-b.bottom-12,acima=b.top-c.top-12,preciso=Math.min(listaRef.current.scrollHeight,190)+6,sobe=preciso>abaixo&&acima>abaixo;setPos({acima:sobe,max:Math.max(96,Math.min(190,sobe?acima:abaixo))});},[aberto,adicionando]);
  useEffect(()=>{if(!aberto)return;const fechar=(e:PointerEvent)=>{if(!ref.current?.contains(e.target as Node))setAberto(false);};document.addEventListener("pointerdown",fechar);return()=>document.removeEventListener("pointerdown",fechar);},[aberto]);
  async function confirmarCategoria(){if(!onAdd||!nome.trim())return;setSalvando(true);try{await onAdd(nome.trim());setAberto(false);setNome("");setAdicionando(false);}finally{setSalvando(false);}}
  return <div className="cofre-launch-select" ref={ref}><button type="button" aria-haspopup="listbox" aria-label={ariaLabel} aria-expanded={aberto} onClick={()=>setAberto(v=>!v)}>{atual?.selo??(IconeAtual?<IconeAtual size={14} style={{color:atual?.cor??undefined}}/>:atual?.cor&&<i style={{background:atual.cor}}/>)}<span>{atual?.label??placeholder}</span><ChevronDown size={14}/></button>{aberto&&<div className="cofre-launch-options" data-acima={pos.acima} style={{maxHeight:pos.max}} ref={listaRef} role="listbox">{!semVazio&&<button type="button" role="option" aria-selected={!value} onClick={()=>{onChange("");setAberto(false);}}><span>{placeholder}</span>{!value&&<Check size={13}/>}</button>}{options.map(o=>{const Icone=icone(o.icone);return <button type="button" role="option" aria-selected={o.value===value} key={o.value} onClick={()=>{onChange(o.value);setAberto(false);}}>{o.selo??(Icone?<Icone size={14} style={{color:o.cor??undefined}}/>:o.cor&&<i style={{background:o.cor}}/>)}<span>{o.label}</span>{o.value===value&&<Check size={13}/>}</button>;})}{onAdd&&<div className="cofre-launch-add-category">{adicionando?<div className="cofre-launch-add-form"><input autoFocus value={nome} onChange={e=>setNome(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void confirmarCategoria();}}} placeholder="Nome da categoria"/><button type="button" onClick={()=>void confirmarCategoria()} disabled={salvando||!nome.trim()}>{salvando?"…":<Check size={14}/>}</button></div>:<button type="button" onClick={()=>setAdicionando(true)}><Plus size={14}/><span>Adicionar categoria</span></button>}</div>}</div>}</div>;
}
function icone(nome?:string|null){return nome?(Icons as unknown as Record<string,Icons.LucideIcon>)[nome]??Icons.Circle:null;}
